[package]
name = "cucumber-runner"
version = "0.1.0"
authors = [
    "Mikhail Sobolev <mss@mawhrin.net>"
]
build = "build.rs"

[dependencies]
colored = "*"
lazy_static = "*"
regex = "*"
rustc-test = "*"

[[test]]
name = "features"
path = "features/features.rs"
harness = false
